---
abstract: 'Plugin for cookie-based authentication'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  CGI::Util: 0
  Catalyst::Test: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-AuthenCookie
requires:
  Catalyst: 5.80
  Digest::SHA: 0
  Moose: 0
  MooseX::Params::Validate: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-AuthenCookie
  repository: http://hg.urth.org/hg/CatalystX-AuthenCookie
version: 0.01
